long_text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Cras semper auctor neque vitae tempus quam pellentesque. Molestie at elementum eu facilisis sed odio. Aliquam vestibulum morbi blandit cursus risus. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Feugiat vivamus at augue eget arcu dictum varius. Tempus egestas sed sed risus pretium quam vulputate. Tempus quam pellentesque nec nam. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Amet dictum sit amet justo donec enim. Quisque egestas diam in arcu cursus. Senectus et netus et malesuada. Scelerisque purus semper eget duis at. Tortor condimentum lacinia quis vel eros donec ac odio. Malesuada bibendum arcu vitae elementum curabitur.
Leo urna molestie at elementum eu facilisis sed odio morbi. Pharetra convallis posuere morbi leo urna molestie at. Vitae tortor condimentum lacinia quis vel. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Ante in nibh mauris cursus mattis molestie a. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Non nisi est sit amet. Libero justo laoreet sit amet cursus sit amet. Varius vel pharetra vel turpis nunc. Neque laoreet suspendisse interdum consectetur libero id. Sit amet nisl suscipit adipiscing. Facilisi morbi tempus iaculis urna id. Velit sed ullamcorper morbi tincidunt ornare massa. Sed egestas egestas fringilla phasellus faucibus. Tincidunt id aliquet risus feugiat in ante metus. Arcu risus quis varius quam. Dictum non consectetur a erat nam. Ac turpis egestas integer eget aliquet nibh. Id ornare arcu odio ut sem nulla.
Libero enim sed faucibus turpis in eu mi bibendum neque. Imperdiet proin fermentum leo vel. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Vulputate dignissim suspendisse in est ante in nibh mauris. Sem integer vitae justo eget magna. A cras semper auctor neque. In fermentum et sollicitudin ac orci phasellus egestas tellus. Porta nibh venenatis cras sed. Nulla pharetra diam sit amet nisl. Ullamcorper sit amet risus nullam eget felis eget nunc. A pellentesque sit amet porttitor eget dolor morbi non. Eu volutpat odio facilisis mauris sit. Dictum varius duis at consectetur lorem donec. Amet justo donec enim diam vulputate.
Mus mauris vitae ultricies leo integer. Laoreet non curabitur gravida arcu ac tortor dignissim. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Eget nunc scelerisque viverra mauris in aliquam sem. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Faucibus interdum posuere lorem ipsum dolor sit amet. Sapien et ligula ullamcorper malesuada proin libero. Euismod quis viverra nibh cras pulvinar mattis nunc. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Aliquam purus sit amet luctus.
Nibh tellus molestie nunc non blandit massa enim nec dui. Ullamcorper sit amet risus nullam eget. Urna et pharetra pharetra massa massa. Elit eget gravida cum sociis natoque penatibus. Condimentum id venenatis a condimentum vitae. Amet risus nullam eget felis. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Habitasse platea dictumst quisque sagittis. Elit sed vulputate mi sit. Enim nunc faucibus a pellentesque sit amet porttitor. Sit amet consectetur adipiscing elit pellentesque habitant. Pharetra convallis posuere morbi leo urna. Mattis nunc sed blandit libero volutpat sed cras ornare. Est velit egestas dui id ornare arcu odio ut. Sed velit dignissim sodales ut eu sem integer. Arcu vitae elementum curabitur vitae.
Lectus sit amet est placerat in egestas erat imperdiet. Erat velit scelerisque in dictum non consectetur. Mauris augue neque gravida in fermentum et. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Pellentesque id nibh tortor id aliquet lectus. Porta lorem mollis aliquam ut porttitor leo a. Posuere ac ut consequat semper viverra nam. Amet volutpat consequat mauris nunc congue. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Tristique magna sit amet purus. Sed sed risus pretium quam vulputate dignissim suspendisse in est. Vel quam elementum pulvinar etiam non quam. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam.
Egestas tellus rutrum tellus pellentesque. Non odio euismod lacinia at. Facilisis sed odio morbi quis commodo odio aenean sed. Metus vulputate eu scelerisque felis imperdiet proin. Feugiat in fermentum posuere urna nec. Nulla porttitor massa id neque. Vulputate sapien nec sagittis aliquam. Etiam sit amet nisl purus in mollis nunc sed id. Scelerisque felis imperdiet proin fermentum leo. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Purus semper eget duis at tellus at urna condimentum.
Tellus molestie nunc non blandit massa enim nec dui. Orci ac auctor augue mauris augue. Amet porttitor eget dolor morbi non arcu risus. Nunc sed id semper risus in hendrerit gravida. Convallis aenean et tortor at risus viverra adipiscing at in. Turpis tincidunt id aliquet risus feugiat in ante metus. Lectus mauris ultrices eros in cursus turpis massa. Orci eu lobortis elementum nibh tellus molestie nunc. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Ultrices eros in cursus turpis massa tincidunt. At risus viverra adipiscing at in tellus integer. Pulvinar sapien et ligula ullamcorper malesuada. Diam vel quam elementum pulvinar etiam non quam lacus. Egestas congue quisque egestas diam in arcu cursus euismod quis. Quis varius quam quisque id diam. Gravida quis blandit turpis cursus in hac habitasse platea dictumst.
Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Posuere morbi leo urna molestie. At quis risus sed vulputate odio ut enim blandit volutpat. Elementum integer enim neque volutpat. Nec sagittis aliquam malesuada bibendum. Nisi lacus sed viverra tellus in hac habitasse. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Vulputate eu scelerisque felis imperdiet. Massa ultricies mi quis hendrerit dolor magna eget. Fringilla urna porttitor rhoncus dolor purus non enim praesent.
Cras sed felis eget velit aliquet sagittis. Ornare suspendisse sed nisi lacus sed viverra. Faucibus et molestie ac feugiat sed. Pulvinar mattis nunc sed blandit libero volutpat sed. Arcu vitae elementum curabitur vitae nunc sed velit dignissim sodales. Neque vitae tempus quam pellentesque nec nam aliquam sem. Habitant morbi tristique senectus et netus. Sed viverra ipsum nunc aliquet. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Dui faucibus in ornare quam viverra orci sagittis eu volutpat.
"""
print(f"'non' repeats {long_text.count('non')} times!")
print(long_text.title())
